Commands Added
adarshPatel509/sociall-cli pull request #2
Opened 2020-12-30 18:20 UTC by utsavk28

2020-12-31 11:12 UTC, adarshPatel509 requested changes

2020-12-31 11:12 UTC, adarshPatel509 commented on commands/feeds.js
>      platform: 'pf'
i thing we need to change 'pf' to 'p' (single char) so we can use -p instead of --pf

2020-12-31 11:12 UTC, adarshPatel509 commented on components/feed/CommentFeed.jsx
> +export default CommentFeed;
we are not using this component anywhere right?

2020-12-31 11:12 UTC, adarshPatel509 commented on components/feed/GithubFeeds.jsx
> +		// console.log(feeds.data);
remove this line.

2020-12-31 11:12 UTC, adarshPatel509 commented on components/feed/InstagramFeeds.jsx
> +					//   const loc_name = location.name
remove all comments.

2020-12-31 11:12 UTC, adarshPatel509 commented on components/feed/RedditFeeds.jsx
> +				// console.log(res.data.children.slice(0, 5))
remove all comments and console.logs

2020-12-31 11:12 UTC, adarshPatel509 commented on components/feed/TwitterFeeds.jsx
> +				// console.log(err);
remove all comments and logs.

2020-12-31 11:12 UTC, adarshPatel509 commented on feed_reply.json
> +        "emoji": "\uD83D\uDCCC",
move this file into feeds folder.

2020-12-31 11:23 UTC, utsavk28 commented on components/feed/CommentFeed.jsx
> +export default CommentFeed;
no

2020-12-31 11:24 UTC, utsavk28 commented on components/feed/GithubFeeds.jsx
> +		// console.log(feeds.data);
the log line ?

2020-12-31 11:25 UTC, adarshPatel509 requested changes

2020-12-31 11:25 UTC, adarshPatel509 commented on commands/notifications.js
>      platform: 'pf'
change to 'p' instead of 'pf'

2020-12-31 11:25 UTC, adarshPatel509 commented on components/notification/InstagramNotifications.jsx
> +                    // console.log(res.old_stories)
remove all comments.

2020-12-31 11:25 UTC, adarshPatel509 commented on components/notification/TwitterNotifications.jsx
> +                // console.log(arr)
remove comments.

2020-12-31 11:28 UTC, adarshPatel509 commented on components/feed/GithubFeeds.jsx
> +		// console.log(feeds.data);
yups. all logs.

2020-12-31 11:28 UTC, adarshPatel509 commented on components/feed/CommentFeed.jsx
> +export default CommentFeed;
delete this file then.

2020-12-31 11:39 UTC, adarshPatel509 requested changes

2020-12-31 11:39 UTC, adarshPatel509 commented on components/post/InstagramPost.jsx
> +				// console.log(imageUpload);
remove all comments.

2020-12-31 11:42 UTC, adarshPatel509 approved these changes

2020-12-31 11:47 UTC, adarshPatel509 requested changes

2020-12-31 11:47 UTC, adarshPatel509 commented on commands/search.js
> +	searchField: "sf",
change 'pf' to 'p' and 'sf' to 's'

2021-01-03 10:48 UTC, adarshPatel509 requested changes

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/follow.js
> +/// Get Latest Feeds command
change the description accordingly. ```Follow users by their userID``` something like that.

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/followers.js
> +    /// Name of the Platform to fetch Feeds
here as well. these are shown on help page.. put appropriate comment for all commands.

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/followers.js
> +/// Get Latest Feeds command
```Get List of Users u follow``` change description

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/following.js
> +/// Get Latest Feeds command
...

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/following.js
> +    /// Name of the Platform to fetch Feeds
..

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/manageUsers/unfollow.js
> +	username: PropTypes.string.isRequired,
add proper description before each options

2021-01-03 10:48 UTC, adarshPatel509 commented on commands/search.js
> +	searchField: PropTypes.string.isRequired,
...

2021-01-07 14:39 UTC, adarshPatel509 requested changes

2021-01-07 14:39 UTC, adarshPatel509 commented on .vscode/launch.json
> +    "configurations": [
remove this file.

2021-01-07 14:39 UTC, adarshPatel509 commented on .vscode/settings.json
> +}
remove this file also.

2021-01-07 14:39 UTC, adarshPatel509 commented on components/feed/GithubFeeds.jsx
> +		const temp =
use proper naming for variables.. is should be totalPages

2021-01-07 14:39 UTC, adarshPatel509 commented on components/feed/TwitterFeeds.jsx
> +		setPgl(temp)
u shouldn't be calculating it here every time there's a button press. then what's the point of having it in state?

2021-01-07 14:39 UTC, adarshPatel509 commented on components/feed/TwitterFeeds.jsx
> +				setFeeds(arr);
do totalpage calculation here. and setPgl.
```
  const totalPages = Math.ceil(arr.length / 5);
  setPgl(totalPages);
```

2021-01-07 14:39 UTC, adarshPatel509 commented on components/search/GithubSearch.jsx
> +        setPgl(temp)
u haven't even declared this state ?? move it to the line 90.

2021-01-07 14:39 UTC, adarshPatel509 commented on components/search/GithubSearch.jsx
> +        setPgl(temp)
and use better variable names please.

2021-01-07 14:39 UTC, adarshPatel509 commented on components/search/GithubSearch.jsx
> +                <Tab name="fosllow"></Tab>
what is this ?

2021-01-07 14:39 UTC, adarshPatel509 commented on components/search/InstagramSearch.jsx
> +		setPgl(temp)
......same issue.. state not declared and move it to line 47

2021-01-07 14:39 UTC, adarshPatel509 commented on components/search/InstagramSearch.jsx
> +	const [feeds, setFeeds] = useState({});
change variable names, its not feeds. use proper descriptive naming

2021-01-07 17:11 UTC, adarshPatel509 commented on components/search/GithubSearch.jsx
> +        return <Loader message=" Fetching Github feeds..." type="dots" />
.....change it

2021-01-07 17:42 UTC, adarshPatel509 commented on components/search/RedditSearch.jsx
> +        return <Loader message=" Fetching Reddit feeds..." type="dots" />
please check these minor error at all places.. change the loading message

2021-01-15 15:52 UTC, adarshPatel509 approved these changes

2021-01-24 08:42 UTC, merged